version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pdf_converter_postgres
    environment:
      POSTGRES_USER: pdf_converter
      POSTGRES_PASSWORD: pdf_converter_dev_password
      POSTGRES_DB: pdf_converter_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pdf_converter"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
